<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es_ES">
<context>
    <name>AnalyserStatus</name>
    <message>
        <location filename="../gui/analyserstatus.ui" line="11"/>
        <source>Analysing net</source>
        <translation>Analizando red</translation>
    </message>
</context>
<context>
    <name>CantFireTransitionException</name>
    <message>
        <location filename="../core/exceptions.h" line="87"/>
        <source>This transition is not active.</source>
        <translation>Esta transición no está sensibilizada.</translation>
    </message>
</context>
<context>
    <name>CmdCreateArc</name>
    <message>
        <location filename="../gui/commands/cmdcreatearc.cpp" line="40"/>
        <source>Create arc</source>
        <translation>Crear arco</translation>
    </message>
</context>
<context>
    <name>CmdCreateArcWithWeight</name>
    <message>
        <location filename="../gui/commands/cmdcreatearcwithweight.cpp" line="41"/>
        <source>Create arc with weight %1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CmdCreateInhibitoArc</name>
    <message>
        <location filename="../gui/commands/cmdcreateinhibitorarc.cpp" line="27"/>
        <source>Create inhibitor arc</source>
        <translation type="unfinished">Crear arco inhibidor</translation>
    </message>
</context>
<context>
    <name>CmdCreateInhibitorArc</name>
    <message>
        <source>Create inhibitor arc</source>
        <translation type="vanished">Crear arco inhibidor</translation>
    </message>
</context>
<context>
    <name>CmdCreatePlace</name>
    <message>
        <location filename="../gui/commands/cmdcreateplace.cpp" line="25"/>
        <source>Create place</source>
        <translation>Crear lugar</translation>
    </message>
</context>
<context>
    <name>CmdCreateTransition</name>
    <message>
        <location filename="../gui/commands/cmdcreatetransition.cpp" line="25"/>
        <source>Create transition</source>
        <translation>Crear transición</translation>
    </message>
</context>
<context>
    <name>CmdRemoveItem</name>
    <message>
        <location filename="../gui/commands/cmdremoveitem.cpp" line="28"/>
        <source>Remove item</source>
        <translation>Eliminar elemento</translation>
    </message>
</context>
<context>
    <name>CmdRemoveItemGroup</name>
    <message>
        <location filename="../gui/commands/cmdremoveitemgroup.cpp" line="38"/>
        <source>Remove item</source>
        <translation type="unfinished">Eliminar elemento</translation>
    </message>
</context>
<context>
    <name>Controller</name>
    <message>
        <location filename="../gui/controller.cpp" line="398"/>
        <source>Export</source>
        <translation>Exportar</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="414"/>
        <source>Image PNG (*.png)</source>
        <translation>Imagen PNG (*.png)</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="426"/>
        <source>PDF (*.pdf)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="441"/>
        <source>Petri Net Graph</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="442"/>
        <source>Generated by Opulus Petri Net Editor</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Post Script (*.ps)</source>
        <translation type="vanished">Post Script (*.ps)</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="436"/>
        <source>Scalable Vector Graphics (*.svg)</source>
        <translation>Scalable Vector Graphics (*.svg)</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="362"/>
        <source>Fire N Random Transitons</source>
        <translation>Disparar N Transiciones Al Azar</translation>
    </message>
    <message>
        <source>How many transitions do you want to fire?</source>
        <translation type="obsolete">¿Cuántas transiciones quieres disparar?</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="362"/>
        <source>How many times do you want to fire random transitions?</source>
        <translation>¿Cuántas veces quiere disparar transiciones al azar?</translation>
    </message>
</context>
<context>
    <name>CovarageGraph</name>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="14"/>
        <source>Coverage Graph</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="26"/>
        <source>Legend</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="112"/>
        <source>Initial marking</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="199"/>
        <source>Dead markings</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="206"/>
        <source>Marking order:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="224"/>
        <source>Zoom out</source>
        <translation type="unfinished">Alejar</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="241"/>
        <source>Zoom in</source>
        <translation type="unfinished">Acercar</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="282"/>
        <source>Net Properties</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CoverageGraph</name>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="56"/>
        <source>Coverage Graph</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="64"/>
        <source>There are no places in this petri net.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="68"/>
        <source>Creating graph...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="116"/>
        <source>Creating graph image with %1 nodes...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="129"/>
        <source>Analyzing Petri Net properties.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="151"/>
        <source>Loading graph image...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="193"/>
        <source>Coverage graph plugin</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="193"/>
        <source>&lt;html&gt;You need graphviz installed on your computer in order to use this plugin. If graphiviz is already installed, make sure that it is in your system path.
You can get graphviz at: &lt;a href=&quot;http://www.graphviz.org&quot;&gt;http://www.graphviz.org&lt;/a&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>DuplicatedIdException</name>
    <message>
        <source>This net already have an item with id: %1</source>
        <translation type="obsolete">Esta red ya tiene un elemento con id: %1</translation>
    </message>
    <message>
        <location filename="../core/exceptions.h" line="101"/>
        <source>This net already has an item with id: %1</source>
        <translation>Esta red ya tiene un elemento con id: %1</translation>
    </message>
</context>
<context>
    <name>DuplicatedNumberException</name>
    <message>
        <location filename="../core/exceptions.h" line="108"/>
        <source>This net already has %2 with number: %1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>IOException</name>
    <message>
        <location filename="../core/exceptions.h" line="122"/>
        <source>%1 at line %2, column %3</source>
        <translation>%1 en la línea %2, columna %3</translation>
    </message>
</context>
<context>
    <name>ItemNotFoundException</name>
    <message>
        <location filename="../core/exceptions.h" line="115"/>
        <source>Item not found, id: %1</source>
        <translation>Elemento no encontrado, id: %1</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../gui/mainwindow.cpp" line="192"/>
        <source>Stop simulation</source>
        <translation>Detener la simulación</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="330"/>
        <location filename="../gui/mainwindow.cpp" line="197"/>
        <source>Start simulation</source>
        <translation>Iniciar la simulación</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.cpp" line="320"/>
        <source>&lt;h1&gt;Opulus version %1&lt;/h1&gt;
&lt;p&gt;Copyright 2007-2015 Opulus developers. Opulus is distributed under the terms of GPL v2, see the COPYING file for details or visit &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Authors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Developer, original author.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Araújo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;cat&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:captainslowpoke@gmail.com&quot;&gt;captainslowpoke@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;zd&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:zettday@gmail.com&quot;&gt;zettday@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;h2&gt;Contributors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Spanish translation.&lt;/dd&gt;
&lt;/dl&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="36"/>
        <source>File</source>
        <translation>Archivo</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="40"/>
        <source>Export to...</source>
        <translation>Exportar a...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="48"/>
        <source>Recent Petri Nets</source>
        <translation>Redes de Petri Recientes</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="63"/>
        <source>Tool</source>
        <translation>Herramienta</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="74"/>
        <location filename="../gui/mainwindow.ui" line="234"/>
        <source>Simulation</source>
        <translation>Simulación</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="82"/>
        <source>Analysis</source>
        <translation>Análisis</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="87"/>
        <source>Help</source>
        <translation>Ayuda</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="104"/>
        <source>View</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="120"/>
        <source>Main</source>
        <translation>Principal</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="134"/>
        <source>Tools</source>
        <translation>Herramientas</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="175"/>
        <location filename="../gui/mainwindow.ui" line="535"/>
        <source>Miniature</source>
        <translation>Miniatura</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="215"/>
        <location filename="../gui/mainwindow.ui" line="546"/>
        <source>Property Editor</source>
        <translation>Editor de Propiedades</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="271"/>
        <source>Advanced Input/Output</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="288"/>
        <source>New Petri Net...</source>
        <translation>Nueva Red de Petri...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="294"/>
        <source>Ctrl+N</source>
        <translation>Ctrl+N</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="303"/>
        <source>Open Petri Net...</source>
        <translation>Abrir Red de Petri...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="309"/>
        <source>Ctrl+O</source>
        <translation>Ctrl+O</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="318"/>
        <source>Quit</source>
        <translation>Salir</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="348"/>
        <source>Select</source>
        <translation>Seleccionar</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="351"/>
        <source>S</source>
        <translation>S</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="363"/>
        <source>Add a place</source>
        <translation>Añadir un lugar</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="366"/>
        <source>P</source>
        <translation>P</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="378"/>
        <source>Add a transition</source>
        <translation>Añadir una transición</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="381"/>
        <source>T</source>
        <translation>T</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="393"/>
        <source>Add an arc</source>
        <translation>Añadir un arco</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="396"/>
        <source>A</source>
        <translation>A</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="408"/>
        <source>Add/remove tokens</source>
        <translation>Añadir/Eliminar marcas</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="417"/>
        <source>Save Petri Net...</source>
        <translation>Guardar Red de Petri...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="420"/>
        <source>Ctrl+S</source>
        <translation>Ctrl+S</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="425"/>
        <source>Save Petri Net as...</source>
        <translation>Guardar Red de Petri como...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="437"/>
        <source>User Manual</source>
        <translation>Manual de Usuario</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="442"/>
        <location filename="../gui/mainwindow.cpp" line="319"/>
        <source>About</source>
        <translation>Acerca de</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="447"/>
        <source>About Qt</source>
        <translation>Acerca de Qt</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="456"/>
        <source>What is this?</source>
        <translation>¿Qué es esto?</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="557"/>
        <source>Input/Output</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Image PNG</source>
        <translation type="vanished">Imagen PNG</translation>
    </message>
    <message>
        <source>Post Script</source>
        <translation type="vanished">Post Script</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="471"/>
        <source>Scalable Vector Graphics (SVG)</source>
        <translation>Scalable Vector Graphics (SVG)</translation>
    </message>
    <message>
        <source>toolBar</source>
        <translation type="obsolete">Barra de herramientas</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="291"/>
        <source>Creates a new empty Petri Net.</source>
        <translation>Crea una Nueva Red de Petri.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="306"/>
        <source>Opens a Petri Net.</source>
        <translation>Abre una Red de Petri.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="333"/>
        <source>Start/Stop simulation.</source>
        <translation>Iniciar/Detener la simulación.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="461"/>
        <source>PNG Image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="466"/>
        <source>PDF Document</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="480"/>
        <source>Fire random transition</source>
        <translation>Disparar una transición al azar</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="489"/>
        <source>Zoom in</source>
        <translation>Acercar</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="501"/>
        <source>Zoom out</source>
        <translation>Alejar</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.cpp" line="214"/>
        <location filename="../gui/mainwindow.cpp" line="252"/>
        <location filename="../gui/mainwindow.cpp" line="266"/>
        <source>Petri Net (*.xml)</source>
        <translation>Red de Petri (*.xml)</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="15"/>
        <source>Opulus[*]</source>
        <translation>Opulus[*]</translation>
    </message>
    <message>
        <source>Opulus version %1
(c) 2007 Hugo Parente Lima, Adauto Trigueiro de Almeida Filho

http://opulus.sf.net/</source>
        <translation type="obsolete">Opulus versión %1(new line)(c) 2007 Hugo Parente Lima, Adauto Trigueiro de Almeida Filho(new line)(new line)http://opulus.sf.net/</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="509"/>
        <source>Fire n random transitions</source>
        <translation>Disparar n transiciones al azar</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="247"/>
        <source>Zoom</source>
        <translation>Zoom</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="260"/>
        <source>Do-Undo</source>
        <translation>Hacer-Deshacer</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="521"/>
        <source>Add an inhibitor arc</source>
        <translation>Añadir un arco inhibidor</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="492"/>
        <source>=</source>
        <translation>=</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="504"/>
        <source>-</source>
        <translation>-</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="524"/>
        <source>I</source>
        <translation>|</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Opulus version %1&lt;/h1&gt;
&lt;p&gt;Copyright 2007-2008 Opulus developers. Opulus is distributed under the terms of GPL v2, see the COPYING file for details or visit &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Authors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Developer, original author.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Araújo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;/dl&gt;
&lt;h2&gt;Contributors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Spanish translation.&lt;/dd&gt;
&lt;/dl&gt;</source>
        <translation type="vanished">&lt;h1&gt;Opulus version %1&lt;/h1&gt;
&lt;p&gt;Copyright 2007-2008 Desarrolladores de Opulus. Opulus se distribuye bajo los términos de la licencia GPL v2, para más detalles lea el archivo COPYING o visite &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Autores&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Desarrollador, autor original.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Desarrollador.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Araújo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Desarrolador.&lt;/dd&gt;
&lt;/dl&gt;
&lt;h2&gt;Contribuidores&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Traducción al castellano.&lt;/dd&gt;
&lt;/dl&gt;</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="91"/>
        <source>Change language</source>
        <translation>Cambiar idioma</translation>
    </message>
</context>
<context>
    <name>MatrixWidget</name>
    <message>
        <location filename="../gui/matrixwidget.ui" line="14"/>
        <source>MatrixWidget</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="26"/>
        <source>Matrix</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="32"/>
        <source>Rows:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="68"/>
        <source>D- Matrix:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="100"/>
        <source>D+ Matrix:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="128"/>
        <source>Columns:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="136"/>
        <source>IO Functions</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="147"/>
        <source>I Function</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="157"/>
        <source>O Function</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="170"/>
        <source>Update Net</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>NoActiveTransitionsException</name>
    <message>
        <location filename="../core/exceptions.h" line="51"/>
        <source>There are no active transitions!</source>
        <translation>¡No hay transiciones sensibilizadas!</translation>
    </message>
    <message>
        <location filename="../core/exceptions.h" line="52"/>
        <source>There are no active transitions after %1 transitions fired!</source>
        <translation>¡No quedan transiciones sensibilizadas tras disparar %1 transiciones!</translation>
    </message>
</context>
<context>
    <name>NoMoreTokensException</name>
    <message>
        <location filename="../core/exceptions.h" line="76"/>
        <source>There are no more tokens on this place.</source>
        <translation>No hay más marcas en este lugar.</translation>
    </message>
</context>
<context>
    <name>PetriNet</name>
    <message>
        <location filename="../core/petrinet.cpp" line="184"/>
        <source>transition</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../core/petrinet.cpp" line="195"/>
        <source>place</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PetriNetScene</name>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="208"/>
        <source>Choose a location to put the place.</source>
        <translation>Seleccione una ubicación para el lugar.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="220"/>
        <source>Choose a location to put the transition.</source>
        <translation>Seleccione una ubicación para la transición.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="232"/>
        <source>Choose a transition or place.</source>
        <translation>Seleccione una transición o lugar.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="238"/>
        <location filename="../gui/petrinetscene.cpp" line="280"/>
        <source>Choose a transition.</source>
        <translation>Seleccione una transición.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="241"/>
        <location filename="../gui/petrinetscene.cpp" line="275"/>
        <source>Choose a place.</source>
        <translation>Seleccione un lugar.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="308"/>
        <source>Use the right mouse button to add a token and the left mouse button to remove a token.</source>
        <translation>Use el botón derecho del ratón para añadir una marca y el izquierdo para eliminar una marca.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="332"/>
        <source>Select a transition to fire.</source>
        <translation>Seleccione una transición que disparar.</translation>
    </message>
    <message>
        <source>You need choose a transition!</source>
        <translation type="obsolete">¡Necesitas escoger una transición!</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="244"/>
        <source>You must choose a transition or place, not this!</source>
        <translation>¡Debe escoger una transición o lugar, no esto!</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="255"/>
        <source>You can not create an arc between these items.</source>
        <translation>No se puede crear un arco entre estos elementos.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="284"/>
        <source>You must choose a place, not this!</source>
        <translation>¡Debe seleccionar un lugar, no esto!</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="292"/>
        <source>Inhibitor arcs must be from a place to a transition.</source>
        <translation>Los arcos inhibidores deben ir de un lugar a una transición.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="337"/>
        <source>You need to choose a transition!</source>
        <translation>¡Debe seleccionar una transición!</translation>
    </message>
</context>
<context>
    <name>Place</name>
    <message>
        <source>You need remove %1 tokens before set the capacity to %2</source>
        <translation type="obsolete">Es necesario eliminar %1 marcas antes de establecer una capacidad de %2</translation>
    </message>
    <message>
        <location filename="../core/place.cpp" line="57"/>
        <source>You need to remove %1 tokens before set the capacity to %2</source>
        <translation>Debe eliminar %1 marcas antes de establecer una capacidad de %2</translation>
    </message>
</context>
<context>
    <name>PlaceCapacityExceedException</name>
    <message>
        <location filename="../core/exceptions.h" line="62"/>
        <source>This place can have only %1 tokens</source>
        <translation>Este lugar sólo puede tener %1 marcas</translation>
    </message>
</context>
<context>
    <name>PropertyEditorModel</name>
    <message>
        <location filename="../gui/propertyeditormodel.cpp" line="138"/>
        <source>Property</source>
        <translation>Propiedad</translation>
    </message>
    <message>
        <location filename="../gui/propertyeditormodel.cpp" line="140"/>
        <source>Value</source>
        <translation>Valor</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../gui/arcpropertyhandler.cpp" line="29"/>
        <source>Weight</source>
        <translation>Peso</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="29"/>
        <source>Name</source>
        <translation>Nombre</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="32"/>
        <source>Capacity</source>
        <translation>Capacidad</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="37"/>
        <source>Tokens</source>
        <translation>Marcas</translation>
    </message>
    <message>
        <location filename="../gui/graphicabstractarc.cpp" line="178"/>
        <source>Remove control point</source>
        <translation>Eliminar punto de control</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="36"/>
        <source>&lt;h1&gt;Analysis Results&lt;/h1&gt;&lt;hr /&gt;&lt;h2&gt;Transitions:&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;Dead : %1 &lt;/li&gt;&lt;li&gt;Potential Dead : %2 &lt;/li&gt;&lt;li&gt;Potential Live :%3 &lt;/li&gt;&lt;li&gt;Live : %4 &lt;/li&gt;&lt;li&gt;Stable : %5 &lt;/li&gt;&lt;/ul&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="53"/>
        <source>&lt;h2&gt;Petri Net:&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;Safe: %1 &lt;/li&gt;&lt;li&gt;Bounded: %2 &lt;/li&gt;&lt;li&gt;Live: %3 &lt;/li&gt;&lt;li&gt;Preserve: %4 &lt;/li&gt;&lt;li&gt;Stritly preserve: %5 &lt;/li&gt;&lt;li&gt;Stable: %6 &lt;/li&gt;&lt;li&gt;Parralel: %7 &lt;/li&gt;&lt;li&gt;Conflicted: %8 &lt;/li&gt;&lt;li&gt;Invertable: %9 &lt;/li&gt;&lt;/ul&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="82"/>
        <source>true</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="82"/>
        <source>false</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Reachability</name>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="20"/>
        <source>Reachability</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="77"/>
        <source>Max L:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="98"/>
        <source>P:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="118"/>
        <source>End Marking</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ReachabilityPlugin</name>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="46"/>
        <source>Reachability of Marking</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="53"/>
        <source>There are no places in this petri net.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="58"/>
        <source>There are no transitions in this petri net.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="65"/>
        <source>Place count in your &apos;End marking&apos; doesn&apos;t equal petri nets place count</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="102"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="102"/>
        <source>Some of cells is empty</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="117"/>
        <source>&lt;h1&gt;Analysis Results&lt;/h1&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="118"/>
        <source>&lt;hr /&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="121"/>
        <source>&lt;li&gt;Marking : (</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="126"/>
        <source>&lt;li&gt;Reachable :</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="128"/>
        <source>true &lt;/li&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="131"/>
        <source>false &lt;/li&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="188"/>
        <source>Prepare...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="195"/>
        <source>Somthing has wrohg... Restart programm and check your petri net</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="235"/>
        <source>Calculating...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../plugins/reachability/results.ui" line="14"/>
        <source>Results</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>TransitionPropertyHandler</name>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="29"/>
        <source>Name</source>
        <translation>Nombre</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Vertical</source>
        <translation>Vertical</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Horizontal</source>
        <translation>Horizontal</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Diagonal 1</source>
        <translation>Diagonal 1</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Diagonal 2</source>
        <translation>Diagonal 2</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="33"/>
        <source>Orientation</source>
        <translation>Orientación</translation>
    </message>
</context>
</TS>
