<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="pt_BR">
<context>
    <name>AnalyserStatus</name>
    <message>
        <location filename="../gui/analyserstatus.ui" line="11"/>
        <source>Analysing net</source>
        <translation>Analisando rede</translation>
    </message>
</context>
<context>
    <name>CantFireTransitionException</name>
    <message>
        <location filename="../core/exceptions.h" line="87"/>
        <source>This transition is not active.</source>
        <translation>Esta transição não esta ativa.</translation>
    </message>
</context>
<context>
    <name>CmdCreateArc</name>
    <message>
        <location filename="../gui/commands/cmdcreatearc.cpp" line="40"/>
        <source>Create arc</source>
        <translation>Criar arco</translation>
    </message>
</context>
<context>
    <name>CmdCreateArcWithWeight</name>
    <message>
        <location filename="../gui/commands/cmdcreatearcwithweight.cpp" line="41"/>
        <source>Create arc with weight %1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CmdCreateInhibitoArc</name>
    <message>
        <location filename="../gui/commands/cmdcreateinhibitorarc.cpp" line="27"/>
        <source>Create inhibitor arc</source>
        <translation type="unfinished">Criar arco inibidor</translation>
    </message>
</context>
<context>
    <name>CmdCreateInhibitorArc</name>
    <message>
        <source>Create inhibitor arc</source>
        <translation type="vanished">Criar arco inibidor</translation>
    </message>
</context>
<context>
    <name>CmdCreatePlace</name>
    <message>
        <location filename="../gui/commands/cmdcreateplace.cpp" line="25"/>
        <source>Create place</source>
        <translation>Criar lugar</translation>
    </message>
</context>
<context>
    <name>CmdCreateTransition</name>
    <message>
        <location filename="../gui/commands/cmdcreatetransition.cpp" line="25"/>
        <source>Create transition</source>
        <translation>Criar transição</translation>
    </message>
</context>
<context>
    <name>CmdRemoveItem</name>
    <message>
        <location filename="../gui/commands/cmdremoveitem.cpp" line="28"/>
        <source>Remove item</source>
        <translation>Remover item</translation>
    </message>
</context>
<context>
    <name>CmdRemoveItemGroup</name>
    <message>
        <location filename="../gui/commands/cmdremoveitemgroup.cpp" line="38"/>
        <source>Remove item</source>
        <translation type="unfinished">Remover item</translation>
    </message>
</context>
<context>
    <name>Controller</name>
    <message>
        <location filename="../gui/controller.cpp" line="398"/>
        <source>Export</source>
        <translation>Exportar</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="414"/>
        <source>Image PNG (*.png)</source>
        <translation>Imagem PNG (*.png)</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="426"/>
        <source>PDF (*.pdf)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="441"/>
        <source>Petri Net Graph</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="442"/>
        <source>Generated by Opulus Petri Net Editor</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="436"/>
        <source>Scalable Vector Graphics (*.svg)</source>
        <translation>Gráfico Vetorial (*.svg)</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="362"/>
        <source>Fire N Random Transitons</source>
        <translation>Disparar N Transições Aleatórias</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="362"/>
        <source>How many times do you want to fire random transitions?</source>
        <translation>Quantos disparos aleatórios você deseja fazer?</translation>
    </message>
</context>
<context>
    <name>CovarageGraph</name>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="14"/>
        <source>Coverage Graph</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="26"/>
        <source>Legend</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="112"/>
        <source>Initial marking</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="199"/>
        <source>Dead markings</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="206"/>
        <source>Marking order:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="224"/>
        <source>Zoom out</source>
        <translation type="unfinished">Reduzir zoom</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="241"/>
        <source>Zoom in</source>
        <translation type="unfinished">Aumentar zoom</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="282"/>
        <source>Net Properties</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CoverageGraph</name>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="56"/>
        <source>Coverage Graph</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="64"/>
        <source>There are no places in this petri net.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="68"/>
        <source>Creating graph...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="116"/>
        <source>Creating graph image with %1 nodes...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="129"/>
        <source>Analyzing Petri Net properties.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="151"/>
        <source>Loading graph image...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="193"/>
        <source>Coverage graph plugin</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="193"/>
        <source>&lt;html&gt;You need graphviz installed on your computer in order to use this plugin. If graphiviz is already installed, make sure that it is in your system path.
You can get graphviz at: &lt;a href=&quot;http://www.graphviz.org&quot;&gt;http://www.graphviz.org&lt;/a&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>DuplicatedIdException</name>
    <message>
        <location filename="../core/exceptions.h" line="101"/>
        <source>This net already has an item with id: %1</source>
        <translation>Esta rede ja possui um item com o id %1</translation>
    </message>
</context>
<context>
    <name>DuplicatedNumberException</name>
    <message>
        <location filename="../core/exceptions.h" line="108"/>
        <source>This net already has %2 with number: %1</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>IOException</name>
    <message>
        <location filename="../core/exceptions.h" line="122"/>
        <source>%1 at line %2, column %3</source>
        <translation>%1 na linha %2, coluna %3</translation>
    </message>
</context>
<context>
    <name>ItemNotFoundException</name>
    <message>
        <location filename="../core/exceptions.h" line="115"/>
        <source>Item not found, id: %1</source>
        <translation>Item não encontrado, id: %1</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../gui/mainwindow.cpp" line="192"/>
        <source>Stop simulation</source>
        <translation>Parar simulação</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="330"/>
        <location filename="../gui/mainwindow.cpp" line="197"/>
        <source>Start simulation</source>
        <translation>Simular</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.cpp" line="320"/>
        <source>&lt;h1&gt;Opulus version %1&lt;/h1&gt;
&lt;p&gt;Copyright 2007-2015 Opulus developers. Opulus is distributed under the terms of GPL v2, see the COPYING file for details or visit &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Authors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Developer, original author.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Araújo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;cat&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:captainslowpoke@gmail.com&quot;&gt;captainslowpoke@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;zd&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:zettday@gmail.com&quot;&gt;zettday@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;h2&gt;Contributors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Spanish translation.&lt;/dd&gt;
&lt;/dl&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="36"/>
        <source>File</source>
        <translation>Arquivo</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="40"/>
        <source>Export to...</source>
        <translation>Exportar para...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="48"/>
        <source>Recent Petri Nets</source>
        <translation>Redes de Petri recentes</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="63"/>
        <source>Tool</source>
        <translation>Ferramenta</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="74"/>
        <location filename="../gui/mainwindow.ui" line="234"/>
        <source>Simulation</source>
        <translation>Simulação</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="82"/>
        <source>Analysis</source>
        <translation>Análise</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="87"/>
        <source>Help</source>
        <translation>Ajuda</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="104"/>
        <source>View</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="120"/>
        <source>Main</source>
        <translation>Principal</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="134"/>
        <source>Tools</source>
        <translation>Ferramentas</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="175"/>
        <location filename="../gui/mainwindow.ui" line="535"/>
        <source>Miniature</source>
        <translation>Miniatura</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="215"/>
        <location filename="../gui/mainwindow.ui" line="546"/>
        <source>Property Editor</source>
        <translation>Editor de propriedades</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="271"/>
        <source>Advanced Input/Output</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="288"/>
        <source>New Petri Net...</source>
        <translation>Nova Rede de Petri...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="294"/>
        <source>Ctrl+N</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="303"/>
        <source>Open Petri Net...</source>
        <translation>Abrir Rede de Petri...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="309"/>
        <source>Ctrl+O</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="318"/>
        <source>Quit</source>
        <translation>Sair</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="348"/>
        <source>Select</source>
        <translation>Selecionar</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="351"/>
        <source>S</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="363"/>
        <source>Add a place</source>
        <translation>Adicionar lugar</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="366"/>
        <source>P</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="378"/>
        <source>Add a transition</source>
        <translation>Adicionar transição</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="381"/>
        <source>T</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="393"/>
        <source>Add an arc</source>
        <translation>Adicionar arco</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="396"/>
        <source>A</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="408"/>
        <source>Add/remove tokens</source>
        <translation>Adicionar/remover fichas</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="417"/>
        <source>Save Petri Net...</source>
        <translation>Salvar Rede de Petri...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="420"/>
        <source>Ctrl+S</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="425"/>
        <source>Save Petri Net as...</source>
        <translation>Salvar Rede de Petri como...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="437"/>
        <source>User Manual</source>
        <translation>Manual do usuário</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="442"/>
        <location filename="../gui/mainwindow.cpp" line="319"/>
        <source>About</source>
        <translation>Sobre</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="447"/>
        <source>About Qt</source>
        <translation>Sobre a Qt</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="456"/>
        <source>What is this?</source>
        <translation>O que é isto?</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="557"/>
        <source>Input/Output</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Image PNG</source>
        <translation type="vanished">Imagem PNG</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="471"/>
        <source>Scalable Vector Graphics (SVG)</source>
        <translation>Gráfico Vetorial (SVG)</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="291"/>
        <source>Creates a new empty Petri Net.</source>
        <translation>Cria uma nova Rede de Petri.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="306"/>
        <source>Opens a Petri Net.</source>
        <translation>Abre uma Rede de Petri.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="333"/>
        <source>Start/Stop simulation.</source>
        <translation>Inicia/Para a simulação.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="461"/>
        <source>PNG Image</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="466"/>
        <source>PDF Document</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="480"/>
        <source>Fire random transition</source>
        <translation>Dispara uma transição aleatória</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="489"/>
        <source>Zoom in</source>
        <translation>Aumentar zoom</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="501"/>
        <source>Zoom out</source>
        <translation>Reduzir zoom</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.cpp" line="214"/>
        <location filename="../gui/mainwindow.cpp" line="252"/>
        <location filename="../gui/mainwindow.cpp" line="266"/>
        <source>Petri Net (*.xml)</source>
        <translation>Rede de Petri (*.xml)</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="15"/>
        <source>Opulus[*]</source>
        <translation>Opulus[*]</translation>
    </message>
    <message>
        <source>Opulus version %1
(c) 2007 Hugo Parente Lima, Adauto Trigueiro de Almeida Filho

http://opulus.sf.net/</source>
        <translation type="obsolete">Opulus versão %1
(c) 2007 Hugo Parente Lima, Adauto Trigueiro de Almeida Filho

http://opulus.sf.net/</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="509"/>
        <source>Fire n random transitions</source>
        <translation>Disparar n transições aleatórias</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="247"/>
        <source>Zoom</source>
        <translation>Zoom</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="260"/>
        <source>Do-Undo</source>
        <translation>Fazer-desfazer</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="521"/>
        <source>Add an inhibitor arc</source>
        <translation>Adicionar arco inibidor</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="492"/>
        <source>=</source>
        <translation>=</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="504"/>
        <source>-</source>
        <translation>-</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="524"/>
        <source>I</source>
        <translation>I</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Opulus version %1&lt;/h1&gt;
&lt;p&gt;Copyright 2007-2008 Opulus developers. Opulus is distributed under the terms of GPL v2, see the COPYING file for details or visit &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Authors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Developer, original author.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Araújo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;/dl&gt;
&lt;h2&gt;Contributors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Spanish translation.&lt;/dd&gt;
&lt;/dl&gt;</source>
        <translation type="vanished">&lt;h1&gt;Opulus versão %1&lt;/h1&gt;&lt;p&gt;Copyright 2007-2008 desenvolvedores do Opulus. Opulus é distribuído sob os termos da GPL v2, para mais detalhes veja o arquivo COPYING ou visite &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;&lt;h2&gt;Autores&lt;/h2&gt;&lt;dl&gt;&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;Desenvolvedor, autor original.&lt;/dd&gt;&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;Desenvolvedor.&lt;/dd&gt;&lt;dt&gt;Clerton Ribeiro de Araújo Filho&lt;/dt&gt;&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;Desenvolvedor.&lt;/dd&gt;&lt;/dl&gt;&lt;h2&gt;Contribuidores&lt;/h2&gt;&lt;dl&gt;&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;Tradução para espanhol.&lt;/dd&gt;&lt;/dl&gt;</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="91"/>
        <source>Change language</source>
        <translation>Alterar idioma</translation>
    </message>
</context>
<context>
    <name>MatrixWidget</name>
    <message>
        <location filename="../gui/matrixwidget.ui" line="14"/>
        <source>MatrixWidget</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="26"/>
        <source>Matrix</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="32"/>
        <source>Rows:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="68"/>
        <source>D- Matrix:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="100"/>
        <source>D+ Matrix:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="128"/>
        <source>Columns:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="136"/>
        <source>IO Functions</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="147"/>
        <source>I Function</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="157"/>
        <source>O Function</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="170"/>
        <source>Update Net</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>NoActiveTransitionsException</name>
    <message>
        <location filename="../core/exceptions.h" line="51"/>
        <source>There are no active transitions!</source>
        <translation>Não há transições ativas!</translation>
    </message>
    <message>
        <location filename="../core/exceptions.h" line="52"/>
        <source>There are no active transitions after %1 transitions fired!</source>
        <translation>Não há transições ativas depois de %1 transições disparadas!</translation>
    </message>
</context>
<context>
    <name>NoMoreTokensException</name>
    <message>
        <location filename="../core/exceptions.h" line="76"/>
        <source>There are no more tokens on this place.</source>
        <translation>Não há mais fichas neste lugar.</translation>
    </message>
</context>
<context>
    <name>PetriNet</name>
    <message>
        <location filename="../core/petrinet.cpp" line="184"/>
        <source>transition</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../core/petrinet.cpp" line="195"/>
        <source>place</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>PetriNetScene</name>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="208"/>
        <source>Choose a location to put the place.</source>
        <translation>Escolha a posição para o novo lugar.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="220"/>
        <source>Choose a location to put the transition.</source>
        <translation>Escolhar a posição para a nova transição.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="232"/>
        <source>Choose a transition or place.</source>
        <translation>Escolhar uma transição ou um lugar.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="238"/>
        <location filename="../gui/petrinetscene.cpp" line="280"/>
        <source>Choose a transition.</source>
        <translation>Escolha uma transição.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="241"/>
        <location filename="../gui/petrinetscene.cpp" line="275"/>
        <source>Choose a place.</source>
        <translation>Escolha um lugar.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="308"/>
        <source>Use the right mouse button to add a token and the left mouse button to remove a token.</source>
        <translation>Use o botão direito do mouse para adicionar fichas e o esquerdo para remover.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="332"/>
        <source>Select a transition to fire.</source>
        <translation>Selecione uma transição para disparar.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="244"/>
        <source>You must choose a transition or place, not this!</source>
        <translation>Você precisa escolher uma transição ou lugar, não isto!</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="255"/>
        <source>You can not create an arc between these items.</source>
        <translation>Você não pode criar um arco entre estes items.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="284"/>
        <source>You must choose a place, not this!</source>
        <translation>Você precisa escolher um lugar, não isto!</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="292"/>
        <source>Inhibitor arcs must be from a place to a transition.</source>
        <translation>Arcos inibidores precisam ser de um lugar para uma transição.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="337"/>
        <source>You need to choose a transition!</source>
        <translation>Você precisa escolher uma transição!</translation>
    </message>
</context>
<context>
    <name>Place</name>
    <message>
        <location filename="../core/place.cpp" line="57"/>
        <source>You need to remove %1 tokens before set the capacity to %2</source>
        <translation>Você precisa remover %1 fichas antes de definir a capacidade para %2</translation>
    </message>
</context>
<context>
    <name>PlaceCapacityExceedException</name>
    <message>
        <location filename="../core/exceptions.h" line="62"/>
        <source>This place can have only %1 tokens</source>
        <translation>Este lugar pode ter apenas %1 fichas</translation>
    </message>
</context>
<context>
    <name>PropertyEditorModel</name>
    <message>
        <location filename="../gui/propertyeditormodel.cpp" line="138"/>
        <source>Property</source>
        <translation>Propriedade</translation>
    </message>
    <message>
        <location filename="../gui/propertyeditormodel.cpp" line="140"/>
        <source>Value</source>
        <translation>Valor</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../gui/arcpropertyhandler.cpp" line="29"/>
        <source>Weight</source>
        <translation>Peso</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="29"/>
        <source>Name</source>
        <translation>Nome</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="32"/>
        <source>Capacity</source>
        <translation>Capacidade</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="37"/>
        <source>Tokens</source>
        <translation>Fichas</translation>
    </message>
    <message>
        <location filename="../gui/graphicabstractarc.cpp" line="178"/>
        <source>Remove control point</source>
        <translation>Remover ponto de controle</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="36"/>
        <source>&lt;h1&gt;Analysis Results&lt;/h1&gt;&lt;hr /&gt;&lt;h2&gt;Transitions:&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;Dead : %1 &lt;/li&gt;&lt;li&gt;Potential Dead : %2 &lt;/li&gt;&lt;li&gt;Potential Live :%3 &lt;/li&gt;&lt;li&gt;Live : %4 &lt;/li&gt;&lt;li&gt;Stable : %5 &lt;/li&gt;&lt;/ul&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="53"/>
        <source>&lt;h2&gt;Petri Net:&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;Safe: %1 &lt;/li&gt;&lt;li&gt;Bounded: %2 &lt;/li&gt;&lt;li&gt;Live: %3 &lt;/li&gt;&lt;li&gt;Preserve: %4 &lt;/li&gt;&lt;li&gt;Stritly preserve: %5 &lt;/li&gt;&lt;li&gt;Stable: %6 &lt;/li&gt;&lt;li&gt;Parralel: %7 &lt;/li&gt;&lt;li&gt;Conflicted: %8 &lt;/li&gt;&lt;li&gt;Invertable: %9 &lt;/li&gt;&lt;/ul&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="82"/>
        <source>true</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="82"/>
        <source>false</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Reachability</name>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="20"/>
        <source>Reachability</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="77"/>
        <source>Max L:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="98"/>
        <source>P:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="118"/>
        <source>End Marking</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>ReachabilityPlugin</name>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="46"/>
        <source>Reachability of Marking</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="53"/>
        <source>There are no places in this petri net.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="58"/>
        <source>There are no transitions in this petri net.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="65"/>
        <source>Place count in your &apos;End marking&apos; doesn&apos;t equal petri nets place count</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="102"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="102"/>
        <source>Some of cells is empty</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="117"/>
        <source>&lt;h1&gt;Analysis Results&lt;/h1&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="118"/>
        <source>&lt;hr /&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="121"/>
        <source>&lt;li&gt;Marking : (</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="126"/>
        <source>&lt;li&gt;Reachable :</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="128"/>
        <source>true &lt;/li&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="131"/>
        <source>false &lt;/li&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="188"/>
        <source>Prepare...</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="195"/>
        <source>Somthing has wrohg... Restart programm and check your petri net</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="235"/>
        <source>Calculating...</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../plugins/reachability/results.ui" line="14"/>
        <source>Results</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>TransitionPropertyHandler</name>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="29"/>
        <source>Name</source>
        <translation>Nome</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Vertical</source>
        <translation>Vertical</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Horizontal</source>
        <translation>Horizontal</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Diagonal 1</source>
        <translation>Diagonal 1</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Diagonal 2</source>
        <translation>Diagonal 2</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="33"/>
        <source>Orientation</source>
        <translation>Orientação</translation>
    </message>
</context>
</TS>
