<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ru_RU" sourcelanguage="en">
<context>
    <name>AnalyserStatus</name>
    <message>
        <location filename="../gui/analyserstatus.ui" line="11"/>
        <source>Analysing net</source>
        <translation>Анализ сети</translation>
    </message>
</context>
<context>
    <name>CantFireTransitionException</name>
    <message>
        <location filename="../core/exceptions.h" line="87"/>
        <source>This transition is not active.</source>
        <translation>Этот переход не активен.</translation>
    </message>
</context>
<context>
    <name>CmdCreateArc</name>
    <message>
        <location filename="../gui/commands/cmdcreatearc.cpp" line="40"/>
        <source>Create arc</source>
        <translation>Создать дугу</translation>
    </message>
</context>
<context>
    <name>CmdCreateInhibitoArc</name>
    <message>
        <location filename="../gui/commands/cmdcreateinhibitorarc.cpp" line="27"/>
        <source>Create inhibitor arc</source>
        <translation>Создать дугу-ингибитор</translation>
    </message>
</context>
<context>
    <name>CmdCreatePlace</name>
    <message>
        <location filename="../gui/commands/cmdcreateplace.cpp" line="25"/>
        <source>Create place</source>
        <translation>Создать позицию</translation>
    </message>
</context>
<context>
    <name>CmdCreateTransition</name>
    <message>
        <location filename="../gui/commands/cmdcreatetransition.cpp" line="25"/>
        <source>Create transition</source>
        <translation>Создать переход</translation>
    </message>
</context>
<context>
    <name>CmdRemoveItem</name>
    <message>
        <location filename="../gui/commands/cmdremoveitem.cpp" line="28"/>
        <source>Remove item</source>
        <translation>Удалить элемент</translation>
    </message>
</context>
<context>
    <name>Controller</name>
    <message>
        <source>Please select and delete transition manually.</source>
        <translation type="vanished">Пожалуйста выберите  и удалите  переход вручную.</translation>
    </message>
    <message>
        <source>Please select and delete place manually.</source>
        <translation type="vanished">Пожалуйста выберите  и удалите  позицию вручную.</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="325"/>
        <source>Fire N Random Transitons</source>
        <translation>Запустить N случайных переходов</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="325"/>
        <source>How many times do you want to fire random transitions?</source>
        <translation>Сколько раз вы хотите запустить случайные переходы?</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="356"/>
        <source>Export</source>
        <translation>Экспорт</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="372"/>
        <source>Image PNG (*.png)</source>
        <translation>Изображение PNG (*.png)</translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="384"/>
        <source>PDF (*.pdf)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="394"/>
        <source>Scalable Vector Graphics (*.svg)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="399"/>
        <source>Petri Net Graph</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/controller.cpp" line="400"/>
        <source>Generated by Opulus Petri Net Editor</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CovarageGraph</name>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="14"/>
        <source>Coverage Graph</source>
        <translation>Граф достижимости</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="26"/>
        <source>Legend</source>
        <translation>Легенда</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="112"/>
        <source>Initial marking</source>
        <translation>Начальная маркировка</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="199"/>
        <source>Dead markings</source>
        <translation type="unfinished">Мертвая маркировка</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="206"/>
        <source>Marking order:</source>
        <translation>Порядок позиций:</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="224"/>
        <source>Zoom out</source>
        <translation>Отдалить</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="241"/>
        <source>Zoom in</source>
        <translation>Приблизить</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.ui" line="282"/>
        <source>Net Properties</source>
        <translation>Свойства сети</translation>
    </message>
</context>
<context>
    <name>CoverageGraph</name>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="56"/>
        <source>Coverage Graph</source>
        <translation>Граф достижимости</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="64"/>
        <source>There are no places in this petri net.</source>
        <translation type="unfinished">В этой сети Петри нет позиций.</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="68"/>
        <source>Creating graph...</source>
        <translation>Создание графа...</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="116"/>
        <source>Creating graph image with %1 nodes...</source>
        <translation type="unfinished">Создание изображения графа с %1 узлами...</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="129"/>
        <source>Analyzing Petri Net properties.</source>
        <translation type="unfinished">Анализ свойств сети Петри.</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="151"/>
        <source>Loading graph image...</source>
        <translation>Загрузка изображения графа...</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="193"/>
        <source>Coverage graph plugin</source>
        <translation>Граф достижимости</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/coveragegraph.cpp" line="193"/>
        <source>&lt;html&gt;You need graphviz installed on your computer in order to use this plugin. If graphiviz is already installed, make sure that it is in your system path.
You can get graphviz at: &lt;a href=&quot;http://www.graphviz.org&quot;&gt;http://www.graphviz.org&lt;/a&gt;&lt;/html&gt;</source>
        <translation type="unfinished">&lt;html&gt;Чтобы использовать этот плагин, вам нужна установленная программа graphviz. Если graphiviz установлен, проверьте что путь до него указан в системной переменной PATH.
Вы можете скачать graphviz перейдя по ссылке: &lt;a href=&quot;http://www.graphviz.org&quot;&gt;http://www.graphviz.org&lt;/a&gt;&lt;/html&gt;</translation>
    </message>
</context>
<context>
    <name>DuplicatedIdException</name>
    <message>
        <location filename="../core/exceptions.h" line="101"/>
        <source>This net already has an item with id: %1</source>
        <translation type="unfinished">В этой сети уже есть элемент с id: %1</translation>
    </message>
</context>
<context>
    <name>DuplicatedNumberException</name>
    <message>
        <location filename="../core/exceptions.h" line="108"/>
        <source>This net already has %2 with number: %1</source>
        <translation type="unfinished">В этой сети уже есть %2 с номером %1</translation>
    </message>
</context>
<context>
    <name>IOException</name>
    <message>
        <location filename="../core/exceptions.h" line="122"/>
        <source>%1 at line %2, column %3</source>
        <translation type="unfinished">%1, линия %2, столбец %3</translation>
    </message>
</context>
<context>
    <name>ItemNotFoundException</name>
    <message>
        <location filename="../core/exceptions.h" line="115"/>
        <source>Item not found, id: %1</source>
        <translation type="unfinished">Элемент не найден, id: %1</translation>
    </message>
</context>
<context>
    <name>MainWindow</name>
    <message>
        <location filename="../gui/mainwindow.ui" line="15"/>
        <source>Opulus[*]</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="36"/>
        <source>File</source>
        <translation>Файл</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="40"/>
        <source>Export to...</source>
        <translation>Экспорт...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="48"/>
        <source>Recent Petri Nets</source>
        <translation type="unfinished">Недавние сети</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="63"/>
        <source>Tool</source>
        <translation>Инструмент</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="74"/>
        <location filename="../gui/mainwindow.ui" line="234"/>
        <source>Simulation</source>
        <translation>Симуляция</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="82"/>
        <source>Analysis</source>
        <translation>Анализ</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="87"/>
        <source>Help</source>
        <translation type="unfinished">Помощь</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="91"/>
        <source>Change language</source>
        <translation type="unfinished">Сменить язык</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="104"/>
        <source>View</source>
        <translation>Вид</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="120"/>
        <source>Main</source>
        <translation>Главная</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="134"/>
        <source>Tools</source>
        <translation>Инструменты</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="175"/>
        <location filename="../gui/mainwindow.ui" line="535"/>
        <source>Miniature</source>
        <translation>Миниатюра</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="215"/>
        <location filename="../gui/mainwindow.ui" line="546"/>
        <source>Property Editor</source>
        <translation>Редактор свойств</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="247"/>
        <source>Zoom</source>
        <translation>Масштаб</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="260"/>
        <source>Do-Undo</source>
        <translation type="unfinished">Повторить-Отменить</translation>
    </message>
    <message>
        <source>Matrix Analysis</source>
        <translation type="obsolete">Ввод</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="271"/>
        <source>Advanced Input/Output</source>
        <translation type="unfinished">Расширенный Ввод/Вывод</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="288"/>
        <source>New Petri Net...</source>
        <translation type="unfinished">Новая сеть...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="291"/>
        <source>Creates a new empty Petri Net.</source>
        <translation type="unfinished">Создать новую сеть Петри.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="294"/>
        <source>Ctrl+N</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="303"/>
        <source>Open Petri Net...</source>
        <translation type="unfinished">Открыть сеть Петри...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="306"/>
        <source>Opens a Petri Net.</source>
        <translation type="unfinished">Открыть сеть Петри.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="309"/>
        <source>Ctrl+O</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="318"/>
        <source>Quit</source>
        <translation>Выход</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="330"/>
        <location filename="../gui/mainwindow.cpp" line="197"/>
        <source>Start simulation</source>
        <translation>Запустить симуляцию</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="333"/>
        <source>Start/Stop simulation.</source>
        <translation>Запустить/Остановить симуляцию.</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="348"/>
        <source>Select</source>
        <translation type="unfinished">Выбор</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="351"/>
        <source>S</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="363"/>
        <source>Add a place</source>
        <translation type="unfinished">Добавить позицию</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="366"/>
        <source>P</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="378"/>
        <source>Add a transition</source>
        <translation type="unfinished">Добавить переход</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="381"/>
        <source>T</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="393"/>
        <source>Add an arc</source>
        <translation type="unfinished">Добавить дугу</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="396"/>
        <source>A</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="408"/>
        <source>Add/remove tokens</source>
        <translation type="unfinished">Добавить/удалить фишки</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="417"/>
        <source>Save Petri Net...</source>
        <translation type="unfinished">Сохранить сеть Петри...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="420"/>
        <source>Ctrl+S</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="425"/>
        <source>Save Petri Net as...</source>
        <translation type="unfinished">Сохранаить сеть Петри как...</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="437"/>
        <source>User Manual</source>
        <translation type="unfinished">Документация пользователя</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="442"/>
        <location filename="../gui/mainwindow.cpp" line="319"/>
        <source>About</source>
        <translation type="unfinished">О программе</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="447"/>
        <source>About Qt</source>
        <translation type="unfinished">Qt</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="456"/>
        <source>What is this?</source>
        <translation type="unfinished">Что это?</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="461"/>
        <source>PNG Image</source>
        <translation type="unfinished">Изображение PNG</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="466"/>
        <source>PDF Document</source>
        <translation type="unfinished">Документ PDF</translation>
    </message>
    <message>
        <source>Image PNG</source>
        <translation type="obsolete">Изображение PNG</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="471"/>
        <source>Scalable Vector Graphics (SVG)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="480"/>
        <source>Fire random transition</source>
        <translation>Запустить случайный переход</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="489"/>
        <source>Zoom in</source>
        <translation>Приблизить</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="492"/>
        <source>=</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="501"/>
        <source>Zoom out</source>
        <translation>Отдалить</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="504"/>
        <source>-</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="509"/>
        <source>Fire n random transitions</source>
        <translation>Запустить N случайных переходов</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="521"/>
        <source>Add an inhibitor arc</source>
        <translation>Добавить дугу-ингибитор</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="524"/>
        <source>I</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.ui" line="557"/>
        <source>Input/Output</source>
        <translation>Ввод/Вывод</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.cpp" line="192"/>
        <source>Stop simulation</source>
        <translation>Остановить симуляцию</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.cpp" line="214"/>
        <location filename="../gui/mainwindow.cpp" line="252"/>
        <location filename="../gui/mainwindow.cpp" line="266"/>
        <source>Petri Net (*.xml)</source>
        <translation>Сеть Петри (*.xml)</translation>
    </message>
    <message>
        <location filename="../gui/mainwindow.cpp" line="320"/>
        <source>&lt;h1&gt;Opulus version %1&lt;/h1&gt;
&lt;p&gt;Copyright 2007-2015 Opulus developers. Opulus is distributed under the terms of GPL v2, see the COPYING file for details or visit &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Authors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Developer, original author.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Araújo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;cat&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:captainslowpoke@gmail.com&quot;&gt;captainslowpoke@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;zd&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:zettday@gmail.com&quot;&gt;zettday@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;h2&gt;Contributors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Spanish translation.&lt;/dd&gt;
&lt;/dl&gt;</source>
        <translation type="unfinished">&lt;h1&gt;Opulus, версия %1&lt;/h1&gt;
&lt;p&gt;Авторское право 2007-2015 Разработчики Opulus. Программа распространяется на условиях лицензии GNU GPL v2, для подробностей смотрите файл COPYING или посетите &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Авторы&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Разработчик, автор идеи.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Разработчик.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Araújo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Разработчик.&lt;/dd&gt;
&lt;dt&gt;cat&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:captainslowpoke@gmail.com&quot;&gt;captainslowpoke@gmail.com&lt;/a&gt;&lt;br&gt;
Разработчик.&lt;/dd&gt;
&lt;dt&gt;zd&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:zettday@gmail.com&quot;&gt;zettday@gmail.com&lt;/a&gt;&lt;br&gt;
Разработчик.&lt;/dd&gt;
&lt;h2&gt;Содействие&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Испанский первод.&lt;/dd&gt;
&lt;/dl&gt;</translation>
    </message>
    <message>
        <source>&lt;h1&gt;Opulus version %1&lt;/h1&gt;
&lt;p&gt;Copyright 2007-2008 Opulus developers. Opulus is distributed under the terms of GPL v2, see the COPYING file for details or visit &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Authors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Developer, original author.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Ara�jo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Developer.&lt;/dd&gt;
&lt;/dl&gt;
&lt;h2&gt;Contributors&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Spanish translation.&lt;/dd&gt;
&lt;/dl&gt;</source>
        <translation type="obsolete">&lt;h1&gt;Opulus версии %1&lt;/h1&gt;
&lt;p&gt;Copyright 2007-2008 Opulus developers. Opulus распространяется в соответствии с положениями лицензии GPL v2. Смотрите файл COPYING для дополнительной информации или посетите &lt;a href=&quot;http://opulus.sf.net&quot;&gt;http://opulus.sf.net&lt;/a&gt;.&lt;/p&gt;
&lt;h2&gt;Авторы&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Hugo Parente Lima&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:hugo.pl@gmail.com&quot;&gt;hugo.pl@gmail.com&lt;/a&gt;&lt;br&gt;
Разработчик, автор идеи.&lt;/dd&gt;
&lt;dt&gt;Adauto Trigueiro de Almeida Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:adautofilho@gmail.com&quot;&gt;adautofilho@gmail.com&lt;/a&gt;&lt;br&gt;
Разработчик.&lt;/dd&gt;
&lt;dt&gt;Clerton Ribeiro de Ara�jo Filho&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;mailto:clertonfilho@gmail.com&quot;&gt;clertonfilho@gmail.com&lt;/a&gt;&lt;br&gt;
Разработчик.&lt;/dd&gt;
&lt;/dl&gt;
&lt;h2&gt;Вклад&lt;/h2&gt;
&lt;dl&gt;
&lt;dt&gt;Carlos Sanchis&lt;/dt&gt;
&lt;dd&gt;&lt;a href=&quot;csanchisb@yahoo.es&quot;&gt;csanchisb@yahoo.es&lt;/a&gt;&lt;br&gt;
Испанский перевод.&lt;/dd&gt;
&lt;/dl&gt;</translation>
    </message>
</context>
<context>
    <name>MatrixWidget</name>
    <message>
        <location filename="../gui/matrixwidget.ui" line="14"/>
        <source>MatrixWidget</source>
        <translation type="unfinished">Ввод</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="26"/>
        <source>Matrix</source>
        <translation>Матрица</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="32"/>
        <source>Rows:</source>
        <translation>Строки:</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="68"/>
        <source>D- Matrix:</source>
        <translation>Матрица D-</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="100"/>
        <source>D+ Matrix:</source>
        <translation>Матрица D+</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="128"/>
        <source>Columns:</source>
        <translation>Столбцы:</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="136"/>
        <source>IO Functions</source>
        <translation type="unfinished">IO-Функции</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="147"/>
        <source>I Function</source>
        <translation type="unfinished">Функция I</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="157"/>
        <source>O Function</source>
        <translation type="unfinished">Функция O</translation>
    </message>
    <message>
        <location filename="../gui/matrixwidget.ui" line="170"/>
        <source>Update Net</source>
        <translation>Обновить сеть</translation>
    </message>
</context>
<context>
    <name>NoActiveTransitionsException</name>
    <message>
        <location filename="../core/exceptions.h" line="51"/>
        <source>There are no active transitions!</source>
        <translation type="unfinished">Нет активных переходов!</translation>
    </message>
    <message>
        <location filename="../core/exceptions.h" line="52"/>
        <source>There are no active transitions after %1 transitions fired!</source>
        <translation type="unfinished">Не осталось активных перехов после запуска %1 переходов!</translation>
    </message>
</context>
<context>
    <name>NoMoreTokensException</name>
    <message>
        <location filename="../core/exceptions.h" line="76"/>
        <source>There are no more tokens on this place.</source>
        <translation type="unfinished">В этой позиции не осталось фишек.</translation>
    </message>
</context>
<context>
    <name>PetriNet</name>
    <message>
        <location filename="../core/petrinet.cpp" line="209"/>
        <source>transition</source>
        <translation type="unfinished">переход</translation>
    </message>
    <message>
        <location filename="../core/petrinet.cpp" line="220"/>
        <source>place</source>
        <translation type="unfinished">позиция</translation>
    </message>
</context>
<context>
    <name>PetriNetScene</name>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="182"/>
        <source>Choose a location to put the place.</source>
        <translation>Выберите место, куда следует поместить позицию.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="194"/>
        <source>Choose a location to put the transition.</source>
        <translation>Выберите место, куда следует поместить переход.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="206"/>
        <source>Choose a transition or place.</source>
        <translation>Выберите позицию или переход.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="212"/>
        <location filename="../gui/petrinetscene.cpp" line="254"/>
        <source>Choose a transition.</source>
        <translation>Выберите переход.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="215"/>
        <location filename="../gui/petrinetscene.cpp" line="249"/>
        <source>Choose a place.</source>
        <translation>Выберите позицию.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="218"/>
        <source>You must choose a transition or place, not this!</source>
        <translation>Вы должны выбрать позицию или переход, а не это!</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="229"/>
        <source>You can not create an arc between these items.</source>
        <translation>Вы не можете создать дугу между этими элементами.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="258"/>
        <source>You must choose a place, not this!</source>
        <translation>Вы должны выбрать позицию, а не это!</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="266"/>
        <source>Inhibitor arcs must be from a place to a transition.</source>
        <translation>Дуги-ингибиторы могут иметь направление только от позиции к переходу.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="282"/>
        <source>Use the right mouse button to add a token and the left mouse button to remove a token.</source>
        <translation>Используйте левую кнопку мыши для добавления фишек, правую кнопку мыши - для удаления.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="306"/>
        <source>Select a transition to fire.</source>
        <translation>Выберите переход для запуска.</translation>
    </message>
    <message>
        <location filename="../gui/petrinetscene.cpp" line="311"/>
        <source>You need to choose a transition!</source>
        <translation>Вам нужно выбрать переход!</translation>
    </message>
</context>
<context>
    <name>Place</name>
    <message>
        <location filename="../core/place.cpp" line="57"/>
        <source>You need to remove %1 tokens before set the capacity to %2</source>
        <translation>Вам нужно удалить %1 фишек, прежде чем устанавливать емкость, равную %2</translation>
    </message>
</context>
<context>
    <name>PlaceCapacityExceedException</name>
    <message>
        <location filename="../core/exceptions.h" line="62"/>
        <source>This place can have only %1 tokens</source>
        <translation>В этой позиции может быть только %1 фишек</translation>
    </message>
</context>
<context>
    <name>PropertyEditorModel</name>
    <message>
        <location filename="../gui/propertyeditormodel.cpp" line="138"/>
        <source>Property</source>
        <translation>Свойство</translation>
    </message>
    <message>
        <location filename="../gui/propertyeditormodel.cpp" line="140"/>
        <source>Value</source>
        <translation>Значение</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../gui/arcpropertyhandler.cpp" line="29"/>
        <source>Weight</source>
        <translation>Вес</translation>
    </message>
    <message>
        <location filename="../gui/graphicabstractarc.cpp" line="178"/>
        <source>Remove control point</source>
        <translation>Удалить контрольную точку</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="29"/>
        <source>Name</source>
        <translation>Имя</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="32"/>
        <source>Capacity</source>
        <translation>Емкость</translation>
    </message>
    <message>
        <location filename="../gui/placepropertyhandler.cpp" line="37"/>
        <source>Tokens</source>
        <translation>Фишки</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="13"/>
        <source>&lt;h1&gt;Analysis Results&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Результаты Анализа&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="14"/>
        <source>&lt;hr /&gt;</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="15"/>
        <source>&lt;h2&gt;Transitions:&lt;/h2&gt;</source>
        <translation>&lt;h2&gt;Переходы:&lt;/h2&gt;</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="16"/>
        <source>&lt;ul&gt;</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="17"/>
        <source>&lt;li&gt; Dead :</source>
        <translation>&lt;li&gt; Мертвые :</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="23"/>
        <source>&lt;li&gt; Potential Dead :</source>
        <translation>&lt;li&gt; Потенциально Мертвые :</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="29"/>
        <source>&lt;li&gt;Potential Live :</source>
        <translation>&lt;li&gt;Потенциально Живые :</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="35"/>
        <source>&lt;li&gt;Live :</source>
        <translation>&lt;li&gt;Живые :</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="41"/>
        <source>&lt;li&gt;Stable :</source>
        <translation>&lt;li&gt;Устойчивые :</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="49"/>
        <source>&lt;h2&gt;Petri Net:&lt;/h2&gt;</source>
        <translation>&lt;h2&gt;Сеть Петри:&lt;/h2&gt;</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="51"/>
        <source>&lt;li&gt;Safe: </source>
        <translation>&lt;li&gt;Безопасность: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="52"/>
        <source>&lt;li&gt;Bounded: </source>
        <translation>&lt;li&gt;Ограниченность: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="53"/>
        <source>&lt;li&gt;Live: </source>
        <translation>&lt;li&gt;Живость: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="54"/>
        <source>&lt;li&gt;Preserve: </source>
        <translation>&lt;li&gt;Сохранение: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="55"/>
        <source>&lt;li&gt;Stritly preserving: </source>
        <translation>&lt;li&gt;Строгое сохранение: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="56"/>
        <source>&lt;li&gt;Stable: </source>
        <translation>&lt;li&gt;Устойчивость: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="57"/>
        <source>&lt;li&gt;Parralel: </source>
        <translation>&lt;li&gt;Параллельность: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="58"/>
        <source>&lt;li&gt;Conflicted: </source>
        <translation>&lt;li&gt;Конфликтность: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="59"/>
        <source>&lt;li&gt;Invertable: </source>
        <translation>&lt;li&gt;Обратимость: </translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="69"/>
        <source>true</source>
        <translation>Да</translation>
    </message>
    <message>
        <location filename="../plugins/coveragegraph/extended/analysis_utils.cpp" line="71"/>
        <source>false</source>
        <translation>Нет</translation>
    </message>
</context>
<context>
    <name>Reachability</name>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="20"/>
        <source>Reachability</source>
        <translation>Достижимость</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="77"/>
        <source>Max L:</source>
        <translation>Макс. L:</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="98"/>
        <source>P:</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.ui" line="118"/>
        <source>End Marking</source>
        <translation>Искомая маркировка</translation>
    </message>
</context>
<context>
    <name>ReachabilityPlugin</name>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="21"/>
        <source>Reachability of Marking</source>
        <translation>Достижимость маркировки</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="28"/>
        <source>There are no places in this petri net.</source>
        <translation>В этой сети Петри нет позиций.</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="33"/>
        <source>There are no transitions in this petri net.</source>
        <translation>В этой сети Петри нет переходов.</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="40"/>
        <source>Place count in your &apos;End marking&apos; doesn&apos;t equal petri nets place count</source>
        <translation>Число позиций в искомой маркировке не соответствует числу позиций в этой сети Петри</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="77"/>
        <source>Error</source>
        <translation>Ошибка</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="77"/>
        <source>Some of cells is empty</source>
        <translation>Некоторые ячейки пусты</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="92"/>
        <source>&lt;h1&gt;Analysis Results&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Результаты Анализа&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="93"/>
        <source>&lt;hr /&gt;</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="96"/>
        <source>&lt;li&gt;Marking : (</source>
        <translation>&lt;li&gt;Маркировка : (</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="101"/>
        <source>&lt;li&gt;Reachable :</source>
        <translation>&lt;li&gt;Достижима :</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="103"/>
        <source>true &lt;/li&gt;</source>
        <translation>Да</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="106"/>
        <source>false &lt;/li&gt;</source>
        <translation>Нет</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="163"/>
        <source>Prepare...</source>
        <translation>Подготовка...</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="170"/>
        <source>Somthing has wrohg... Restart programm and check your petri net</source>
        <translation>Что-то пошло не так. Перезапустите программу или проверьте сеть Петри</translation>
    </message>
    <message>
        <location filename="../plugins/reachability/reachability.cpp" line="210"/>
        <source>Calculating...</source>
        <translation>Вычисление...</translation>
    </message>
</context>
<context>
    <name>Results</name>
    <message>
        <location filename="../plugins/reachability/results.ui" line="14"/>
        <source>Results</source>
        <translation>Результаты</translation>
    </message>
</context>
<context>
    <name>TransitionPropertyHandler</name>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="29"/>
        <source>Name</source>
        <translation>Имя</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Vertical</source>
        <translation>Вертикальная</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Horizontal</source>
        <translation>Горизонтальная</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Diagonal 1</source>
        <translation>Диагональная 1</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="32"/>
        <source>Diagonal 2</source>
        <translation>Диагональная 2</translation>
    </message>
    <message>
        <location filename="../gui/transitionpropertyhandler.cpp" line="33"/>
        <source>Orientation</source>
        <translation>Ориентация</translation>
    </message>
</context>
</TS>
