name: C/C++ CI

on: [push]

jobs:
  Linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with: 
        fetch-depth: 1
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-9 qt5-default libqt5svg5-dev libqt5xml5 qttools5-dev qttools5-dev-tools cmake libeigen3-dev graphviz
         
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DGRAPHVIZ_BACKEND=SHARED ..
        cmake --build .
        
  MacOS:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
      with: 
        fetch-depth: 1
    - name: Prepare
      run: |
        brew install qt5 cmake graphviz eigen
         
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DGRAPHVIZ_BACKEND=SHARED ..
        cmake --build .
